name: Bank
version: ${project.version}
main: me.sebbaindustries.bank.BankPlugin
depend: [Vault]
api-version: 1.15
authors: [SebbaIndustries, Frcsty]
description: 'A custom bank plugin featuring an intuitive simple usage'
website: 'sebbaindustries.com/bank'